blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainblog.urls'))
]

mainblog/urls.py
from django.urls import path
from mainblog.views import Index, PostDetail, addComment, PostCategory, About

app_name = 'mainblog'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('recents/<slug:slug>/', PostDetail.as_view() ,name='detailpost'),
    path('recents/<slug:post_slug>/submitComment/', addComment,name='addcomment'),
    path('category/<str:string>/', PostCategory.as_view(),name='category'),
    path('category/<str:string>/<slug:slug>/', PostDetail.as_view() ,name='categorypost'),
    path('about/', About.as_view(), name='about')
]

mainblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.utils.text import slugify

class Post(models.Model):
    title = models.CharField(max_length=150, verbose_name='Title')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='author')
    descr = models.CharField(max_length=200, verbose_name='Description')
    body = models.TextField(verbose_name='Post Body')
    pub_date = models.DateTimeField(auto_now_add=True)
    post_type = models.TextChoices('post_type','Food Travel Lifestyle Fashion')
    category = models.CharField(max_length=20, choices=post_type.choices, default='Food')
    slug = models.SlugField(default="my-post-name", max_length=200)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title + ' | ' + str(self.author)

class Comment(models.Model):
    message = models.TextField()
    email = models.EmailField(blank=True)
    username = models.CharField(max_length=100, default="anonymous")
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.message

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['message', 'email', 'username']

class Category(models.Model):
    name = models.CharField(max_length = 20, verbose_name="category_name")

mainblog/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.views import generic
from .models import Post, Comment, CommentForm, Category


class Index(generic.ListView):
    template_name = 'mainblog/index.html'
    model = Post
    paginate_by = 6

    def get_queryset(self):
        return Post.objects.order_by('-pub_date')
    

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'mainblog/postdetail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm
        post = Post.objects.get(slug=self.kwargs['slug'])
        context["comments"] = Comment.objects.filter(post=post)
        context["category"] = Category.objects.get(name=post.category)
        return context

class PostCategory(generic.ListView):
    model = Post
    template_name = 'mainblog/postCategory.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.filter(category=self.kwargs['string'])
        context["category"] = Category.objects.get(name=self.kwargs['string'])
        return context
    

def addComment(request, post_slug, *args):
    myform = CommentForm(request.POST)

    if myform.is_valid():
        username = myform.cleaned_data['username']
        email = myform.cleaned_data['email']
        message = myform.cleaned_data['message']
        c = Comment(username=username, email=email, message=message, post=Post.objects.get(slug=post_slug))
        c.save()
        if not args:
            return HttpResponseRedirect(reverse('mainblog:detailpost', args=(post_slug,)))
        return HttpResponseRedirect(reverse('mainblog:categorypost', args=(post_slug, *args,)))

class About(generic.TemplateView):
    template_name = './mainblog/about.html'

mainblog/templates/base-post.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Pepper's Corner</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'mainblog/styles.css' %}">
        <link href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    </head>
    <body>
        <div class='navbar navbar-expand navbar-light bg-light '>
            <a class='navbar-brand header-name' href="{% url 'mainblog:index' %}">CHEF TOLU PEPPER</a>
                <nav class="navbar-nav ml-auto socials">
                    <li class='nav-item col px-md-2'><a href="#" class='nav-link fab fa-facebook'></a></li>
                    <li class='nav-item col px-md-2'><a href="#" class='nav-link fab fa-youtube'></a></li>
                    <li class='nav-item col px-md-2'><a href="#" class='nav-link fab fa-instagram'></a></li>
                    <li class='nav-item col px-md-2'><a href="#" class='nav-link fab fa-whatsapp'></a></li>
                </nav>
            </div>
        <div>
            <div class='brand-logo'></div>
        </div>

        <div class="navbar navbar-expand-lg navbar-light bg-light">
            <button type='button' class="navbar-toggler" data-toggle="collapse" data-target="#navbarmenu" aria-expanded="false" aria-controls="navbar"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarmenu">
                <ul class='navbar-nav mx-auto'>
                    <li class='nav-item'><a href="{% url 'mainblog:category' 'Food' %}" class="unique-link m-link">FOOD</a></li>
                    <li class='nav-item'><a href="{% url 'mainblog:category' 'Lifestyle' %}" class="custom-link m-link">LIFESTYLE</a></li>
                    <li class='nav-item'><a href="{% url 'mainblog:category' 'Travel' %}" class="custom-link m-link">TRAVEL</a></li>
                    <li class='nav-item'><a href="{% url 'mainblog:category' 'Fashion' %}" class="custom-link m-link">FASHION</a></li>
                </ul>
            </div>
        </div>

        </div>
        {% if category.name == 'Lifestyle' %}
            <div class="w-100"  style="background-image:url('{% static 'mainblog/images/lifestyle.jpg' %}'); height:70vh; background-position:bottom right; background-attachment: fixed;">
                <p class="category-name">{{ category.name }}</p>
            </div>
        {% elif category.name == 'Food' %}
            <div class="w-100"  style="background-image:url('{% static 'mainblog/images/food.jpg' %}'); height:70vh; background-position:center right; background-attachment: fixed;">
                <p class="category-name">{{ category.name }}</p>
            </div>
        {% elif category.name == 'Travel' %}
            <div class="w-100"  style="background-image:url('{% static 'mainblog/images/travelB.jpg' %}'); height:70vh; background-position:center; background-attachment: fixed;">
                <p class="category-name">{{ category.name }}</p>
            </div>
        {% else%}
            <div class="w-100"  style="background-image:url('{% static 'mainblog/images/fashionB.jpg' %}'); height:70vh; background-position:center; background-attachment: fixed;">
                <p class="category-name">{{ category.name }}</p>
            </div>
        {% endif %}

    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <footer class="bg-dark text-center text-white">
        <div class="container p-4">
        <section class="mb-4">
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-youtube"></i
            ></a>
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-twitter"></i
            ></a>
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-whatsapp"></i
            ></a>
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-instagram"></i
            ></a>
            </a>
        </section>
        <section class="mb-4">
            Hey, I'm Tolu Oriyomi, the author and creator of this blog. Follow me on my Socials to get Updated and to discover more of my work, Thanks!!
        </section>
        </div>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
         Copyright &copy; 2020 <strong>Chef Tolu</strong>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </body>
</html>

mainblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Pepper's Corner</title>
        {% load static %}
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
        <link rel="stylesheet" href="{% static 'mainblog/styles.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    </head>
    <body>
        <div class='navbar navbar-expand navbar-light bg-light '>
            <a class='navbar-brand header-name' href="{% url 'mainblog:index' %}">CHEF TOLU PEPPER</a>
                <nav class="navbar-nav ml-auto" id="socials">
                    <li class='nav-item col px-md-2'><a href="#" class='nav-link fab fa-facebook'></a></li>
                    <li class='nav-item col px-md-2'><a href="#" class='nav-link fab fa-youtube'></a></li>
                    <li class='nav-item col px-md-2'><a href="#" class='nav-link fab fa-instagram'></a></li>
                    <li class='nav-item col px-md-2'><a href="#" class='nav-link fab fa-whatsapp'></a></li>
                </nav>
            </div>
        <div class="w-100">
            <div class='brand-logo'></div>
        </div>

        <div class="navbar navbar-expand-lg navbar-light bg-light">
            <button type='button' class="navbar-toggler" data-toggle="collapse" data-target="#navbarmenu" aria-expanded="false" aria-controls="navbar"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarmenu">
                <ul class='navbar-nav mx-auto'>
                    <li class='nav-item'><a href="{% url 'mainblog:category' 'Food' %}" class="unique-link m-link">FOOD</a></li>
                    <li class='nav-item'><a href="{% url 'mainblog:category' 'Lifestyle' %}" class="custom-link m-link">LIFESTYLE</a></li>
                    <li class='nav-item'><a href="{% url 'mainblog:category' 'Travel' %}" class="custom-link m-link">TRAVEL</a></li>
                    <li class='nav-item'><a href="{% url 'mainblog:category' 'Fashion' %}" class="custom-link m-link">FASHION</a></li>
                </ul>
            </div>
        </div>

        <div class="food-carousel">
            <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselIndicators" data-slide-to="1"></li>
                <li data-target="#carouselIndicators" data-slide-to="2"></li>
                <li data-target="#carouselIndicators" data-slide-to="3"></li>
                </ol>
                <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="{% static 'mainblog/images/foodB.jpg' %}" alt="First slide" >
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Interesting topics on Food and Health in the Food Section</h3>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'mainblog/images/fashion.jpg' %}" alt="Second slide" >
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Dress to impress, Learn more by viewing the Fashion Section</h3>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'mainblog/images/travel.jpg' %}" alt="Third slide" >
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Find Detailed Articles on expediting and the likes all in the Travel Section</h3>
                    </div>
                </div>
                 <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'mainblog/images/lifestyleB.jpg' %}" alt="Fourth slide" >
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Having a notable Lifestyle is very important, Discover More in the Lifestyle Section</h3>
                    </div>
                </div>
                </div>
                <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
                </a>
            </div>
        </div>

    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <footer class="bg-dark text-center text-white">
        <div class="container p-4">
        <section class="mb-4">
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-youtube"></i
            ></a>
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-twitter"></i
            ></a>
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-whatsapp"></i
            ></a>
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-instagram"></i
            ></a>
            </a>
        </section>
        <section class="mb-4">
            Hey, I'm Tolu Oriyomi, the author and creator of this blog. Follow me on my Socials to get Updated and to discover more of my work, Thanks!!
        </section>
        </div>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
         Copyright &copy; 2020 <strong>Chef Tolu</strong>
        </div>
    </footer>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </body>
</html>

mainblog/templates/mainblog/about.html
{% extends 'base.html' %}
{% block content %}
    <section class="container-fluid" height="300px">
        <div>No content yet sorry...</div>
    </section>
{% endblock %}

mainblog/templates/mainblog/index.html
{% extends 'base.html' %}
{% block content %}
    <h2 class='ml-auto bg-light p-2 mt-1'>RECENTS</h2>
    <div class="container-fluid">
        <div class='post-collective'>
            {% for post in page_obj %}
                <div class='post-content'>
                    <h3>{{ post.title }}</h3>
                    <p class="badge badge-secondary disabled">{{ post.category }}</p>
                    <hr>
                    <div>
                        <p class="lead">{{ post.descr }}<p>
                        <p class='badge badge-light'>{{ post.pub_date }}</p>
                    </div>
                    <a class="btn btn-primary read-btn" href="{% url 'mainblog:detailpost' post.slug %}">Read More</a>
                </div>
            {% endfor %}
        </div>

        <div class="pagination justify-content-center page-tab">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">first</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                </li>
                {% endif %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last</a>
                </li>
                {% endif %}
            </span>
        </div>
    </div>

    
{% endblock %}

mainblog/templates/mainblog/postCategory.html
{% extends 'base-post.html' %}
{% block content %}

    <div ><div class="bg-dark comment-tag">{{ posts|length }} in {{ category.name }}</div></div>
     <div class='post-collective mx-auto' width="600px">
            {% for post in posts %}
               <div class='post-content'>
                    <h3>{{ post.title }}</h3>
                    <p class="badge badge-secondary disabled">{{ post.category }}</p>
                    <hr>
                    <div>
                        <p class="lead">{{ post.descr }}<p>
                        <p class='badge badge-light'>{{ post.pub_date }}</p>
                    </div>
                    <a class="btn btn-primary read-btn" href="{% url 'mainblog:detailpost' post.slug %}">Read More</a>
                </div>
            {% endfor %}
        </div>
{% endblock %}

mainblog/templates/mainblog/postdetail.html
{% extends 'base-post.html' %}
{% block content %}
    <div class="m-3 p-3 br-2 bg-light">
        <h2 class="font-weight-bold font-italic post-title">{{ post.title }}</h2> 
        <small>{{ post.pub_date }} by {{ post.author }}</small>
    </div>
    <section class=''>
        <p class="text-muted" style="font-size:4vh;">{{ post.body }}</p>
    </section>

     <div class='container-fluid'>
        <div class="bg-dark comment-tag ">Comments</div>

        <form method='POST' action="{% url 'mainblog:addcomment' post.slug %}">
        {% csrf_token %}
            <div class="form-group">
                <label>Username: </label>
                <input type='text' name='username' class='form-control w-50' required>
            </div>
            <div class="form-group">
                <label>Email: </label>
                <input type='email' name='email' class='form-control w-50' required>
            </div>
            <div class="form-group">
                <label>Comment: </label>
                <input type='text' name='message' class='form-control w-50' required>
            </div>
            <input type="submit" value="Post" class="btn btn-success btn-lg">
        </form>

        <ul class="list-group">
            {% for c in comments %}
                <li class="list-group-item m-3 w-50">
                    <h4>{{ c.username }}</h4>
                    <p>{{ c.message }}</p>
                </li>
                <br>
            {% endfor %}
        </div>

        <br>
    </div>
{% endblock %}